assembly:
  stage: test
  image: debian:trixie-slim
  before_script:
    - apt-get update
    - apt-get install -y --no-install-recommends binutils-x86-64-linux-gnu binutils-i686-linux-gnu dosbox
    - x86_64-linux-gnu-as -o olq_linux_x86-64.o olq_linux_x86-64.s
    - x86_64-linux-gnu-ld -o olq_linux_x86-64 olq_linux_x86-64.o
    - i686-linux-gnu-as -o olq_linux_x86.o olq_linux_x86.s
    - i686-linux-gnu-ld -o olq_linux_x86 olq_linux_x86.o
    - i686-linux-gnu-as -o olq_dos.o olq_dos.s
    - i686-linux-gnu-ld -Ttext=0x100 -e 0x100 --oformat binary -o olq_dos.com olq_dos.o
    - export SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy
  script:
    - ./olq_linux_x86-64 | cmp olq_linux_x86-64.s -
    - ./olq_linux_x86 | cmp olq_linux_x86.s -
    - printf "[autoexec]\nMOUNT C \"$PWD\"\nC:\nOLQ_DOS.COM > OLQ_DOS.LOG\nEXIT" > dosbox.conf
    - dosbox
    - cmp olq_dos.s OLQ_DOS.LOG
  rules:
    - changes:
      - olq*.s
awk:
  stage: test
  image: busybox:1-musl
  script:
    - echo | awk -f olq.awk | cmp olq.awk -
  rules:
    - changes:
      - olq.awk
c:
  stage: test
  image: gcc:16-trixie
  before_script:
    - gcc -Wall -Wextra -Werror -ansi -pedantic -o olq olq.c
    - gcc -Wall -Wextra -Werror -ansi -pedantic -o olq_ascii olq_ascii.c
    - gcc -Wall -Wextra -Werror -ansi -pedantic -o olq_posix olq_posix.c
  script:
    - ./olq | cmp olq.c -
    - ./olq_ascii | cmp olq_ascii.c -
    - ./olq_posix | cmp olq_posix.c -
  rules:
    - changes:
      - olq*.c
clojure:
  stage: test
  image: clojure:temurin-25-alpine
  script:
    - clojure -M olq.cljc | cmp olq.cljc -
  rules:
    - changes:
      - olq.cljc
dotnet:
  image: mcr.microsoft.com/dotnet/sdk:10.0-alpine
  script:
    - dotnet run --file olq.cs | cmp olq.cs -
    - dotnet run --file olq_cs9.cs | cmp olq_cs9.cs -
    - cp olq.fs olq.fsx
    - dotnet fsi olq.fsx | cmp olq.fs -
  rules:
    - changes:
      - olq*.cs
      - olq.fs
emojicode:
  stage: test
  image: esolang/emojicode:2.6.0
  script:
    - emojicode olq.emojic | cmp olq.emojic -
  rules:
    - changes:
      - olq.emojic
erlang:
  stage: test
  image: erlang:29-alpine
  script:
    - erlc olq.erl
    - escript olq.beam | cmp olq.erl -
  rules:
    - changes:
      - olq.erl
forth:
  stage: test
  image: debian:bookworm-slim
  before_script:
    - apt-get update -qq
    - apt-get install -y gforth
  script:
    - gforth olq.fth -e BYE | cmp olq.fth -
  rules:
    - changes:
      - olq.fth
go:
  stage: test
  image: golang:1-alpine
  script:
    - go run olq.go | cmp olq.go -
  rules:
    - changes:
      - olq.go
haskell:
  stage: test
  image: haskell:9-slim
  script:
    - runghc olq.hs | cmp olq.hs -
  rules:
    - changes:
      - olq.hs
java:
  stage: test
  image: eclipse-temurin:25-jdk-alpine
  before_script:
    - javac olq.java
  script:
    - java Q | cmp olq.java -
  rules:
    - changes:
      - olq.java
javascript:
  stage: test
  image: node:26-alpine
  script:
    - node olq.js | cmp olq.js -
    - node olq_es6.js | cmp olq_es6.js -
  rules:
    - changes:
      - olq*.js
kotlin:
  stage: test
  image: eclipse-temurin:25-jdk-alpine
  before_script:
    - apk -U add bash
    - wget https://github.com/JetBrains/kotlin/releases/download/v2.4.0/kotlin-compiler-2.4.0.zip
    - unzip kotlin-compiler-2.4.0.zip
    - kotlinc/bin/kotlinc olq.kt
  script:
    - kotlinc/bin/kotlin OlqKt | cmp olq.kt -
  rules:
    - changes:
      - olq.kt
lua:
  stage: test
  image: alpine:3
  before_script:
    - apk update
    - apk add lua5.5
  script:
    - lua5.5 olq.lua | cmp olq.lua -
  rules:
    - changes:
      - olq.lua
perl:
  stage: test
  image: perl:5-slim
  script:
    - perl olq.pl | cmp olq.pl -
    - perl olq_ascii.pl | cmp olq_ascii.pl -
  rules:
    - changes:
      - olq*.pl
php:
  stage: test
  image: php:8-cli-alpine
  script:
    - php olq.php | cmp olq.php -
  rules:
    - changes:
      - olq.php
python:
  stage: test
  image: python:3-alpine
  script:
    - python olq.py | cmp olq.py -
    - python olq_percent.py | cmp olq_percent.py -
  rules:
    - changes:
      - olq*.py
rust:
  stage: test
  image: rust:1-alpine
  before_script:
    - rustc olq.rs
  script:
    - ./olq | cmp olq.rs -
  rules:
    - changes:
      - olq.rs
ruby:
  stage: test
  image: ruby:3-alpine
  script:
    - ruby olq.rb | cmp olq.rb -
  rules:
    - changes:
      - olq.rb
scheme:
  stage: test
  image: alpine:3
  before_script:
    - apk update
    - apk add guile
  script:
    - guile olq.scm | cmp olq.scm -
  rules:
    - changes:
      - olq.scm
shell:
  stage: test
  image: busybox:1-musl
  script:
    - sh olq.sh | cmp olq.sh -
  rules:
    - changes:
      - olq.sh
